// app/layout.tsx
import type { Metadata } from "next";
import { Schibsted_Grotesk } from "next/font/google";
import "./globals.css";
import { Navbar } from "./_components/menu";



const schibstedGrotesk = Schibsted_Grotesk({

  variable: "--font-schibstedGrotesk",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        
        className={`${schibstedGrotesk.variable} antialiased bg-[#F6F6F6] text-neutral-900`}
        
      >|
      <Navbar />
        {children}
      </body>
    </html>
  );
}